version: '2'

services:
  api:
    build:
      context: .
    environment:
      MIX_ENV: dev
    command: mix start_app
    ports: 
      - "4000:4000"
    links: 
      - postgres
    volumes:
      - .:/app

  front_end:
    build:
      context: front_end
    command: npm start
    ports: 
      - "8080:8080"
    volumes:
      - ./front_end/app:/app/app

  postgres:
    image: postgres
