version: '2'

services:
  api: &base
    build:
      context: .
    command: mix start_app
    environment:
      MIX_ENV: dev
    ports: 
      - "4000:4000"
    links: 
      - postgres
    volumes:
      - .:/app

  front_end:
    build:
      context: front_end
    command: npm start
    ports: 
      - "8080:8080"
    volumes:
      - ./front_end/app:/app/app
    environment:
      VIRTUAL_HOST: reader.docker

  postgres:
    image: postgres
    ports: 
      - "5432:5432"

  api_test:
    <<: *base
    environment:
      MIX_ENV: test
    ports:
      - "4001:4001"
    command: mix ecto.create
